spring:
  application:
    name: aiagent

  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            model: gemini-3.5-flash-lite

server:
  port: 8080